language: minimal
services:
  - docker
before_install:
  - docker pull lennartwittkuhn/talk-rdm:latest
  - docker run --rm -v $PWD:/home lennartwittkuhn/talk-rdm /bin/sh -c "cd /home; make all"
script:
  - make all
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: public
  github-token: $PAT_GITHUB_PAGES
  keep-history: true
  target_branch: gh-pages
  on:
    branch: master