language: minimal
services:
  - docker
before_install:
  - docker pull lennartwittkuhn/talk-rdm:latest
script:
  - docker run --rm -v $PWD:/home lennartwittkuhn/talk-rdm /bin/sh -c "cd /home; make all"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $PAT_GITHUB_PAGES
  keep_history: true
  target_branch: gh-pages
  on:
    branch: master